options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build the Spring Boot application using Maven
  - name: 'maven:3.8.3-jdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']
  
  # 2. Build the Docker image using the Dockerfile at the repository root
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA', '.']
  
  # 3. Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA']
  
  # 4. Authenticate with GKE using your cluster details
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials autopilot-cluster-1 --zone us-central1
  
  # 5. Deploy to GKE using Kubernetes manifests in the k8s/ directory
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
  
  # 6. (Optional) List the deployed pods for verification
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['get', 'pods']

images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA'
