options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build the JAR with Maven
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']

  # 2. Build and tag the Docker image as :latest
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/riftco-apps/demo:latest', '.']

  # 3. Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/riftco-apps/demo:latest']

  # 4. Deploy to GKE
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials cost-optimized-cluster-1 --region us-central1
        kubectl apply -f k8s/
        kubectl rollout restart deployment/demo-deployment -n riftco-tradesense # Force pull of :latest
        kubectl get pods -n riftco-tradesense

images:
  - 'gcr.io/riftco-apps/demo:latest'