options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1. Build with Maven
  - name: 'maven:3.8.5-openjdk-17'
    entrypoint: 'mvn'
    args: ['clean', 'package']
  
  # 2. Build and push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA']

  # 3. Get cluster credentials and run kubectl commands
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Authenticate with your cluster
        gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1

        # Apply your manifests from k8s/
        kubectl apply -f k8s/

        # (Optional) Verify pods
        kubectl get pods

images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app:$SHORT_SHA'
