spring:
  application:
    name: demo
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    probes:
      enabled: true