
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-ingress
  namespace: riftco-tradesense
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "tradesense-cert"
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: platform.riftco.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: demo-service
            port:
              number: 8080