apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  type: LoadBalancer
  selector:
    app: demo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080